// Friendly aliases over generated schema types. Frontends import these instead of
// reaching into components['schemas'] — generated/types.ts stays untouched.
import type { components } from './generated/types'

type S = components['schemas']

export type User = S['User']
export type Author = S['Author']
export type UserKind = S['UserKind']
export type Participant = S['Participant']
export type ParticipantRole = S['ParticipantRole']
export type ParticipantsEvent = S['ParticipantsEvent']
export type RoomBot = S['RoomBot']
export type Room = S['Room']
export type RoomVisibility = S['RoomVisibility']
export type RoomRole = S['RoomRole']
export type Item = S['Item']
export type Media = S['Media']
export type MediaType = S['MediaType']
export type ReactionType = S['ReactionType']
export type ReactionSummary = S['ReactionSummary']
export type StreamEvent = S['StreamEvent']
export type StreamEventType = S['StreamEventType']
export type PaginatedMeta = S['PaginatedMeta']

export type GuestInput = S['GuestInput']
export type RegisterInput = S['RegisterInput']
export type LoginInput = S['LoginInput']
export type UpdateMeInput = S['UpdateMeInput']
export type CreateRoomInput = S['CreateRoomInput']
export type UpdateRoomInput = S['UpdateRoomInput']
export type JoinRoomInput = S['JoinRoomInput']
export type SendMessageInput = S['SendMessageInput']
export type ReplyToItemInput = S['ReplyToItemInput']
export type ShareMessageInput = S['ShareMessageInput']
export type Message = S['Message']

// Workspaces (doc/09)
export type Workspace = S['Workspace']
export type WorkspaceRole = S['WorkspaceRole']
export type MemberStatus = S['MemberStatus']
export type WorkspaceMember = S['WorkspaceMember']
export type WorkspaceInvite = S['WorkspaceInvite']
export type Team = S['Team']
export type TeamRole = S['TeamRole']
export type Activity = S['Activity']
export type ActionExecution = S['ActionExecution']
export type CreateWorkspaceInput = S['CreateWorkspaceInput']
export type UpdateWorkspaceInput = S['UpdateWorkspaceInput']
export type UpdateWorkspaceMemberInput = S['UpdateWorkspaceMemberInput']
export type CreateWorkspaceInviteInput = S['CreateWorkspaceInviteInput']
export type CreateTeamInput = S['CreateTeamInput']
export type UpdateTeamInput = S['UpdateTeamInput']

// Contacts, accounts, tags, notes, links (doc/09 slice 1)
export type Contact = S['Contact']
export type ContactRef = S['ContactRef']
export type ContactPoint = S['ContactPoint']
export type ContactPointInput = S['ContactPointInput']
export type ContactPointKind = S['ContactPointKind']
export type ContactMatch = S['ContactMatch']
export type MatchResult = S['MatchResult']
export type Account = S['Account']
export type AccountRef = S['AccountRef']
export type AccountType = S['AccountType']
export type RecordStatus = S['RecordStatus']
export type Tag = S['Tag']
export type Note = S['Note']
export type RecordLink = S['RecordLink']
export type CreateContactInput = S['CreateContactInput']
export type UpdateContactInput = S['UpdateContactInput']
export type SetContactAccountInput = S['SetContactAccountInput']
export type CreateAccountInput = S['CreateAccountInput']
export type UpdateAccountInput = S['UpdateAccountInput']
export type CreateTagInput = S['CreateTagInput']
export type UpdateTagInput = S['UpdateTagInput']
export type CreateNoteInput = S['CreateNoteInput']
export type CreateRecordLinkInput = S['CreateRecordLinkInput']

// Documents platform contract (doc/10).
export type Document = S['Document']
export type DocumentDescriptor = S['DocumentDescriptor']
export type DocumentCapabilities = S['DocumentCapabilities']
export type CreateDocumentInput = S['CreateDocumentInput']
export type UpdateDocumentInput = S['UpdateDocumentInput']
export type DocumentGrant = S['DocumentGrant']
export type DocumentRoomLink = S['DocumentRoomLink']
export type DocumentRelation = S['DocumentRelation']
export type GridTable = S['GridTable']
export type DocumentMaterialization = S['DocumentMaterialization']
export type ImportDocumentCsvInput = S['ImportDocumentCsvInput']
export type DatasetDefinition = S['DatasetDefinition']
export type ContactsDatasetQuery = S['ContactsDatasetQuery']
export type ContactsDatasetRow = S['ContactsDatasetRow']
export type DatasetQueryInput = S['DatasetQueryInput']
export type DatasetWriteInput = S['DatasetWriteInput']
export type DatasetManifest = S['DatasetManifest']
export type DatasetExport = S['DatasetExport']
export type CreateContactsReviewInput = S['CreateContactsReviewInput']
export type ContactImport = S['ContactImport']
export type ContactImportRow = S['ContactImportRow']
export type ImportField = S['ImportField']
export type ImportProposal = S['ImportProposal']
export type CreateContactImportInput = S['CreateContactImportInput']
