import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { chromium } from '@playwright/test'
const output = await mkdtemp(join(tmpdir(), 'map-editor-'))
const browser = await chromium.launch()
try {
  execFileSync('pnpm', ['exec', 'esbuild', 'tests/map-editor.fixture.tsx', '--bundle', '--jsx=automatic', '--define:import.meta.env={}', `--outfile=${join(output, 'fixture.js')}`], { cwd: fileURLToPath(new URL('../', import.meta.url)), stdio: 'pipe' })
  const script = await readFile(join(output, 'fixture.js'), 'utf8')
  const css = await readFile(join(output, 'fixture.css'), 'utf8')
  const context = await browser.newContext({ viewport: { width: 1200, height: 800 } })
  await context.route('https://map.test/**', route => route.fulfill({ contentType: 'text/html', body: `<style>:root{--ink:white;--line:#777;--line-width:1px;--surface-deep:#08090a;--mono:monospace}body{margin:0}#root{height:800px}${css}</style><div id="root"></div><script>${script}</script>` }))
  const page = await context.newPage()
  const errors = []; page.on('pageerror', e => { errors.push(e.message); console.error(e.message) })
  await page.goto('https://map.test/')
  const stage = page.locator('.work-map')
  await stage.waitFor()
  assert.equal(await page.locator('.work-node').count(), 2, 'Offscreen nodes are culled')
  const box = await stage.boundingBox()
  const focal = { x: box.x + 174, y: box.y + 136 }
  const transform = () => page.locator('.map-world').evaluate(el => { const m = new DOMMatrix(getComputedStyle(el).transform); return { x: m.e, y: m.f, zoom: m.a } })
  await page.mouse.move(focal.x, focal.y)
  await page.mouse.wheel(0, -346.57359)
  await page.waitForFunction(() => new DOMMatrix(getComputedStyle(document.querySelector('.map-world')).transform).a > 1.99999)
  let v = await transform()
  assert.ok(Math.abs((174 - v.x) / v.zoom - 174) < .01, 'Wheel zoom anchors x')
  assert.ok(Math.abs((136 - v.y) / v.zoom - 136) < .01, 'Wheel zoom anchors y')
  const node = page.locator('.work-node').filter({ has: page.locator('input[value="One"]') })
  let n = await node.boundingBox()
  await page.mouse.move(n.x + 20, n.y + 10); await page.mouse.down(); await page.mouse.move(n.x - 380, n.y - 190, { steps: 8 }); await page.mouse.up()
  let first = await page.evaluate(() => window.mapStore.getState().docs[0].nodes[0])
  assert.ok(Math.abs(first.x + 100) < .1 && Math.abs(first.y) < .1, 'Dragging uses world coordinates and crosses zero')
  await page.getByTitle('Green', { exact: true }).click()
  assert.equal(await page.evaluate(() => window.mapStore.getState().docs[0].nodes[0].color), '#33FF33')
  await page.getByRole('button', { name: 'Fit selection', exact: true }).click()
  await page.waitForTimeout(50)
  n = await node.boundingBox()
  assert.ok(n.x >= box.x && n.x + n.width <= box.x + box.width + 1)
  await page.getByTitle('Reset zoom to 100%').click()
  await page.waitForTimeout(50)
  assert.equal((await transform()).zoom, 1)
  // Paste follows the current cursor, even after fitting a distant viewport.
  await page.mouse.move(box.x + 500, 500)
  await page.keyboard.press('Control+c'); await page.keyboard.press('Control+v')
  assert.equal(await page.evaluate(() => window.mapStore.getState().docs[0].nodes.length), 1003)
  await page.getByRole('button', { name: 'Round', exact: true }).click()
  const created = await page.evaluate(() => window.mapStore.getState().docs[0].nodes.at(-1))
  v = await transform()
  assert.ok(Math.abs((created.x + 74) * v.zoom + v.x - box.width / 2) < 1, 'Creation is centered in viewport')
  // Pan leaves persisted coordinates untouched.
  const before = await page.evaluate(() => JSON.stringify(window.mapStore.getState().docs[0].nodes))
  await page.mouse.move(box.x + 700, 650); await page.mouse.down(); await page.mouse.move(box.x + 750, 700, { steps: 8 }); await page.mouse.up()
  assert.equal(await page.evaluate(() => JSON.stringify(window.mapStore.getState().docs[0].nodes)), before)
  await page.reload(); await stage.waitFor()
  // Resize at 2x zoom uses world units.
  await page.mouse.move(box.x + 174, 136); await page.mouse.wheel(0, -346.57359)
  await page.waitForFunction(() => new DOMMatrix(getComputedStyle(document.querySelector('.map-world')).transform).a > 1.99999)
  n = await node.boundingBox()
  await page.mouse.click(n.x + 20, n.y + 10)
  const resize = await node.getByRole('button', { name: 'Resize', exact: true }).boundingBox()
  await page.mouse.move(resize.x + resize.width / 2, resize.y + resize.height / 2); await page.mouse.down()
  await page.mouse.move(resize.x + resize.width / 2 + 80, resize.y + resize.height / 2 + 40, { steps: 5 }); await page.mouse.up()
  first = await page.evaluate(() => window.mapStore.getState().docs[0].nodes[0])
  assert.ok(Math.abs(first.width - 188) < .1 && Math.abs(first.height - 92) < .1, 'Resize is zoom independent')
  await page.reload(); await stage.waitFor()
  // Connector endpoints remain interactive through the transformed scene.
  n = await node.boundingBox(); await page.mouse.move(n.x + n.width - 1, n.y + n.height / 2)
  const source = await node.locator('[data-pos="right"]').boundingBox()
  const targetNode = page.locator('.work-node[data-shape="diamond"]')
  const target = await targetNode.locator('[data-pos="left"]').boundingBox()
  await page.mouse.move(source.x + source.width / 2, source.y + source.height / 2); await page.mouse.down()
  await page.mouse.move(target.x + target.width / 2, target.y + target.height / 2, { steps: 5 }); await page.mouse.up()
  assert.equal(await page.evaluate(() => window.mapStore.getState().docs[0].edges.length), 2)
  // Real browser touch events, with fingers starting over shapes.
  const cdp = await context.newCDPSession(page)
  const touch = async (type, points) => cdp.send('Input.dispatchTouchEvent', { type, touchPoints: points.map((p, id) => ({ x: p[0], y: p[1], id })) })
  const x1 = box.x + 174, x2 = box.x + 474
  await touch('touchStart', [[x1, 136]])
  await touch('touchStart', [[x1, 136], [x2, 136]])
  await touch('touchMove', [[x1 - 100, 136], [x2 + 100, 136]])
  await touch('touchEnd', [])
  await page.waitForTimeout(80)
  v = await transform()
  assert.ok(Math.abs(v.zoom - 5 / 3) < .02, `Pinch zoom ${v.zoom}`)
  assert.ok(Math.abs((324 - v.x) / v.zoom - 324) < .1, 'Pinch preserves focal point')
  // Independent viewports still exchange world-space live drags and edits.
  const peer = await context.newPage(); await peer.goto('https://map.test/'); await peer.locator('.work-map').waitFor()
  await page.getByTitle('Reset zoom to 100%').click(); await page.waitForTimeout(50)
  n = await node.boundingBox()
  await page.mouse.move(n.x + 20, n.y + 10); await page.mouse.down(); await page.mouse.move(n.x + 60, n.y + 30, { steps: 5 })
  await peer.waitForFunction(() => parseFloat(document.querySelector('.work-node').style.left) > 130)
  await page.mouse.up()
  await peer.waitForFunction(() => window.mapStore.getState().docs[0].nodes[0].x > 130)
  await page.getByTitle('Green', { exact: true }).click()
  await peer.waitForFunction(() => window.mapStore.getState().docs[0].nodes[0].color === '#33FF33')
  assert.deepEqual(errors, [])
  console.log('Map browser checks passed: culling, focal zoom, negative drag, green, fit/reset, paste, creation, pan, resize, connectors, touch pinch, and collaboration.')
} finally { await browser.close(); await rm(output, { recursive: true, force: true }) }
