import { db } from '@project/db'
import { afterEach } from 'vitest'

// Clean between tests — children before parents for FK constraints.
afterEach(async () => {
  // Workspaces (doc/09) before users: Workspace.createdBy restricts user deletes.
  // Chatbot host + company profile (doc/12), proposals (doc/13): before members.
  await db.agentProposal.deleteMany()
  await db.contactBrief.deleteMany()
  await db.companyProfileRevision.deleteMany()
  await db.companyFact.deleteMany()
  await db.companyScalarSource.deleteMany()
  await db.companyProfile.deleteMany()
  await db.workflowAnswer.deleteMany()
  await db.workflowRun.deleteMany()
  await db.workspaceChannel.deleteMany()
  await db.documentRelation.deleteMany()
  await db.documentRoomLink.deleteMany()
  await db.documentGrant.deleteMany()
  await db.document.deleteMany()
  await db.activitySubject.deleteMany()
  await db.activity.deleteMany()
  await db.actionExecution.deleteMany()
  await db.recordLink.deleteMany()
  await db.note.deleteMany()
  await db.recordImage.deleteMany()
  await db.interest.deleteMany()
  await db.inventoryStockMovement.deleteMany()
  await db.inventory.deleteMany()
  await db.teamMember.deleteMany()
  await db.team.deleteMany()
  await db.workspaceInvite.deleteMany()
  await db.workspaceMember.deleteMany()
  await db.workspace.deleteMany()
  await db.botDecision.deleteMany()
  await db.botRoute.deleteMany()
  await db.botOnce.deleteMany()
  await db.roomBot.deleteMany()
  await db.botLine.deleteMany()
  await db.botAsset.deleteMany()
  await db.bot.deleteMany()
  await db.userMute.deleteMany()
  await db.reaction.deleteMany()
  await db.media.deleteMany()
  await db.item.updateMany({ data: { parentId: null } }) // self-FK: unlink before delete
  await db.item.deleteMany()
  await db.message.deleteMany() // after items (FK) and media (SetNull)
  await db.roomMember.deleteMany()
  await db.room.deleteMany()
  await db.session.deleteMany()
  await db.profile.deleteMany()
  await db.user.deleteMany()
})
