// Query keys shared by all hooks — invalidation only works if these match exactly.
export const keys = {
  me: ['me'] as const,
  rooms: (params?: object) => ['rooms', 'list', params ?? {}] as const,
  roomsAll: ['rooms'] as const,
  myRooms: ['rooms', 'mine'] as const,
  room: (roomId: string) => ['room', roomId] as const,
  items: (roomId: string) => ['items', roomId] as const,
  item: (itemId: string) => ['item', itemId] as const,
  participants: (roomId: string) => ['participants', roomId] as const,
  roomBots: (roomId: string) => ['roomBots', roomId] as const,
  mutes: ['mutes'] as const,
  workspaces: ['workspaces'] as const,
  workspace: (workspaceId: string) => ['workspaces', workspaceId] as const,
  workspaceMembers: (workspaceId: string) => ['workspaces', workspaceId, 'members'] as const,
  workspaceInvites: (workspaceId: string) => ['workspaces', workspaceId, 'invites'] as const,
  teams: (workspaceId: string) => ['workspaces', workspaceId, 'teams'] as const,
  workspaceActivity: (workspaceId: string) => ['workspaces', workspaceId, 'activity'] as const,
  workspaceActions: (workspaceId: string, params?: object) => ['workspaces', workspaceId, 'actions', params ?? {}] as const,
  // Contacts & co. live under the workspace, so one invalidation of ['workspaces', id]
  // refreshes records, timelines and the activity feed together.
  contacts: (workspaceId: string, params?: object) => ['workspaces', workspaceId, 'contacts', 'list', params ?? {}] as const,
  contact: (workspaceId: string, contactId: string) => ['workspaces', workspaceId, 'contacts', contactId] as const,
  inventory: (workspaceId: string, params?: object) => ['workspaces', workspaceId, 'inventory', 'list', params ?? {}] as const,
  inventoryItem: (workspaceId: string, inventoryId: string) => ['workspaces', workspaceId, 'inventory', inventoryId] as const,
  interests: (workspaceId: string, contactId: string) => ['workspaces', workspaceId, 'contacts', contactId, 'interests'] as const,
  accounts: (workspaceId: string, params?: object) => ['workspaces', workspaceId, 'accounts', 'list', params ?? {}] as const,
  account: (workspaceId: string, accountId: string) => ['workspaces', workspaceId, 'accounts', accountId] as const,
  timeline: (workspaceId: string, subject: string) => ['workspaces', workspaceId, 'timeline', subject] as const,
  tags: (workspaceId: string) => ['workspaces', workspaceId, 'tags'] as const,
  notes: (workspaceId: string, subject: string) => ['workspaces', workspaceId, 'notes', subject] as const,
  links: (workspaceId: string, filter: object) => ['workspaces', workspaceId, 'links', filter] as const,
  roomLinks: (roomId: string) => ['roomLinks', roomId] as const,
  inbox: (workspaceId: string, params?: object) => ['workspaces', workspaceId, 'inbox', params ?? {}] as const,
}
