// Query keys shared by all hooks — invalidation only works if these match exactly.
export const keys = {
  me: ['me'] as const,
  rooms: (params?: object) => ['rooms', 'list', params ?? {}] as const,
  roomsAll: ['rooms'] as const,
  myRooms: ['rooms', 'mine'] as const,
  room: (roomId: string) => ['room', roomId] as const,
  items: (roomId: string) => ['items', roomId] as const,
  item: (itemId: string) => ['item', itemId] as const,
  participants: (roomId: string) => ['participants', roomId] as const,
  roomBots: (roomId: string) => ['roomBots', roomId] as const,
  mutes: ['mutes'] as const,
  workspaces: ['workspaces'] as const,
  workspace: (workspaceId: string) => ['workspaces', workspaceId] as const,
  workspaceMembers: (workspaceId: string) => ['workspaces', workspaceId, 'members'] as const,
  workspaceInvites: (workspaceId: string) => ['workspaces', workspaceId, 'invites'] as const,
  teams: (workspaceId: string) => ['workspaces', workspaceId, 'teams'] as const,
  workspaceActivity: (workspaceId: string) => ['workspaces', workspaceId, 'activity'] as const,
  workspaceActions: (workspaceId: string, params?: object) => ['workspaces', workspaceId, 'actions', params ?? {}] as const,
}
